// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO
{
    public partial class People
    {
        public People()
        {
            Users = new HashSet<Users>();
        }

        public string Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int? ClientTypeId { get; set; }
        public int? ContactTypeId { get; set; }
        public bool SupportStaff { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public int? CompanyId { get; set; }
        public int? DepartmentId { get; set; }
        public bool Enabled { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual ClientTypes ClientType { get; set; }
        public virtual Companies Company { get; set; }
        public virtual ContactTypes ContactType { get; set; }
        public virtual Deparments Department { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}