// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO
{
    public partial class UserPermissions
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int PermissionId { get; set; }

        public virtual Permissions Permission { get; set; }
        public virtual Users User { get; set; }
    }
}